server:
  port: 8076

spring:
  application:
    name: product-service
    not_found: 404
    bad_request: 400
    conflict: 409
    ok: 200
  datasource:
    url: jdbc:mysql://localhost:3306/appdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
