server:
  port: 8077

spring:
  application:
    name: payment-service
    not_found: 404
    bad_request: 400
    conflict: 409
    ok: 200
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 2
    url: jdbc:mysql://localhost:3306/appdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
